### ISSUE TITLE
Attention to escape character ` \ `

### ISSUE THREAD

**Issue by gdelvecchiodelvecchio** [CarloLucibello/FatGraphs.jl#103]
At /src/shortestpaths/astar.jl line 49 there is an escape character \. It should be removed in order to avoid an invalid syntax ERROR during compilation. In Julia 0.7.0. there are also several WARNINGS easy to fix.

**Comment by CarloLucibello** [comment]
could you try to test the julia 0.7/1.0 compatible version that has just been tagged and merged on METADATA? Does it work for you?

**Comment by gdelvecchiodelvecchio** [comment]
Tested on Julia 0.7.0. with the following code:

`
using Erdos, ErdosExtras

g = CompleteGraph(100)

em = EdgeMap(g, e->rand(e))

matching = minimum_weight_perfect_matching(g, em).mate
spanning = minimum_spanning_tree(g, rand(nv(g), nv(g)))

`

and it worked though ErdosExtras is still giving WARNINGS but that's another package.

**Comment by CarloLucibello** [comment]
I'll update ErdosExtras soon, should be straightforward

Il gio 8 nov 2018, 08:05 Giuseppe Del Vecchio Del Vecchio <
notifications@github.com> ha scritto:
