### ISSUE TITLE
Failed to precompile Erdos, error building BlossomV

### ISSUE THREAD

**Issue by CBongiova** [CarloLucibello/FatGraphs.jl#93]
I have a problem precompiling module Erdos, related to BlossomV (see the screenshot). 

![screenshot 68](https://user-images.githubusercontent.com/24223801/35865272-5e86e460-0b54-11e8-9b19-f3fe05164066.png)

Then, when I run BinDeps.debug("BlossomV") I get the following message 
INFO: Reading build script...
The package declares 2 dependencies.
 - Library "blossom5int32"
    - Providers:
      - Simple Build Process
 - Library "blossom5float64"
    - Providers:
      - Simple Build Process

But again, building BlossomV gives me: 
![screenshot 69](https://user-images.githubusercontent.com/24223801/35865386-a4de3ba2-0b54-11e8-9e2c-7847abb1ee51.png)

Does anyone know how to fix this issue?

**Comment by CarloLucibello** [comment]
mhmhm, I think BlossomV.jl  package doesn't support windows. Maybe I should move it to the ErdosExtra package so to ensure better compatibility of Erdos. You were looking for the matching algorithm given by BlossomV?

**Comment by CBongiova** [comment]
Actually I would like to use Erdos to run Endmonds-Karp algorithm (maximum flow). I know this is also possible on LightGraphs. The main issue is that in LightGraphs the function maximum_flow doesn't return the s-t mincut.

**Comment by CarloLucibello** [comment]
I made a branch without  BlossomV, please try it with
```julia
Pkg.checkout("Erdos", "excise")
```
and let me know if it works for you

**Comment by CBongiova** [comment]
Hey Carlo, I actually got this new error
![screenshot 70](https://user-images.githubusercontent.com/24223801/35869178-be411a1a-0b5e-11e8-84a5-a3ac0c3f41c7.png)

**Comment by CarloLucibello** [comment]
weird. Try
```julia
Pkg.checkout("Erdos")
Pkg.checkout("Erdos","excise")
```
if that doesn't work try also `Pkg.update()`

**Comment by CBongiova** [comment]
Thank you!! It works now :)

**Comment by CarloLucibello** [comment]
thank you for the bug report! Let's keep this open until I merge the branch in master

**Comment by CarloLucibello** [comment]
@CBongiova is merged in master now, so you can revert to Pkg.checkout("Erdos")
